services:
  annotation-backend:
    build: 
      context: ./annotation-backend-copy
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./annotation-backend-copy:/app
      - ./uploads:/app/uploads
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/annotation
      - CORS_ORIGINS=["http://localhost:3000","http://0.0.0.0:3000","http://127.0.0.1:3000","http://localhost:3001","http://0.0.0.0:3001","http://127.0.0.1:3001","http://annotation-admin-ui","http://annotation-ui"]
    depends_on:
      - db 

  annotation-admin-ui:
    build:
      context: ./annotation-admin-ui-copy
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    volumes:
      - ./annotation-admin-ui-copy:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://annotation-backend:8000
    depends_on:
      - annotation-backend

  annotation-ui:
    build:
      context: ./annotation-ui
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    volumes:
      - ./annotation-ui:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - annotation-backend

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=annotation
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 