services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: annotation
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: 
      context: ./annotation-backend-tfc
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/annotation
      SYNC_DATABASE_URL: postgresql://postgres:postgres@db:5432/annotation
      SECRET_KEY: "your-secret-key-here"  # Change this in production
      CORS_ORIGINS: '["http://localhost:3001"]'
    ports:
      - "8001:8000"
    depends_on:
      db:
        condition: service_healthy

  admin-ui:
    build:
      context: ./annotation-admin-ui
      args:
        VITE_API_URL: http://localhost:8001
    ports:
      - "3001:80"
    depends_on:
      - backend

volumes:
  postgres_data: 